/*
 * solver.h — C FFI for the poker-solver local GTO solver.
 *
 * This header is GENERATED by cbindgen from
 *   crates/solver-ffi/src/lib.rs
 * Do NOT edit it by hand — run `cargo build -p solver-ffi` to regenerate.
 *
 * --------------------------------------------------------------------
 * Intended consumer: ~/Desktop/Poker Panel/ (macOS Swift app).
 *
 * Linking from Swift:
 *   - Add libsolver_ffi.a (static) or libsolver_ffi.dylib (dynamic) to
 *     the Xcode target.
 *   - Include this header via a bridging header, or import it with
 *     @_silgen_name for per-symbol shims.
 *   - See crates/solver-ffi/examples/swift-harness/ for a minimal
 *     swiftc invocation that exercises the whole path.
 *
 * Lifecycle:
 *   1. SolverHandle *h = solver_new();
 *   2. (loop) solver_solve(h, &in, &out) or solver_lookup_cached(&in, &out);
 *   3. solver_free(h);
 *
 * Return codes (see `SolverStatus` enum):
 *    0  Ok
 *    1  CacheMiss   — caller may fall back to solver_solve()
 *   -1  InvalidInput
 *   -2  InternalError (a Rust panic was caught at the FFI boundary)
 *   -3  OutputTooSmall
 *
 * Concurrency:
 *   - Each SolverHandle is single-threaded. For concurrent callers
 *     allocate one handle per thread.
 *   - solver_lookup_cached() is thread-safe (pure lookup, no handle).
 *   - solver_version() is thread-safe and returns a static string —
 *     do not free it.
 *
 * ABI stability:
 *   - The layout of HandState and SolveResult is part of the contract.
 *     Any change here is a BREAKING change to Poker Panel and bumps the
 *     solver major version. Use solver_version() on the consumer side
 *     to verify a match at startup.
 */


#ifndef POKER_SOLVER_FFI_H
#define POKER_SOLVER_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/*
 Returned error codes from `solver_solve` / `solver_lookup_cached`.
 */
enum SolverStatus
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  /*
   Success.
   */
  Ok = 0,
  /*
   Cache miss — caller may fall through to live solve.
   */
  CacheMiss = 1,
  /*
   Invalid input (null pointer, malformed HandState, etc.).
   */
  InvalidInput = -1,
  /*
   Panic caught at FFI boundary.
   */
  InternalError = -2,
  /*
   Output buffer too small.
   */
  OutputTooSmall = -3,
};
#ifndef __cplusplus
typedef int32_t SolverStatus;
#endif // __cplusplus

/*
 Opaque handle — owns scratch memory for reuse across calls.

 Pokeer Panel creates one per thread/solve-queue via `solver_new`.
 */
typedef struct SolverHandle {
  uint8_t _private[0];
} SolverHandle;

/*
 Input: the full description of a spot to solve.

 Laid out for cheap FFI copy. All data is owned; no pointers into
 caller memory.
 */
typedef struct HandState {
  /*
   Board cards (0..5 used, rest ignored).
   */
  uint8_t board[5];
  /*
   Number of valid board cards.
   */
  uint8_t board_len;
  /*
   Hero's range weights (1326 f32s).
   */
  float hero_range[1326];
  /*
   Villain's range weights.
   */
  float villain_range[1326];
  /*
   Pot size in chips.
   */
  uint32_t pot;
  /*
   Effective stack in chips.
   */
  uint32_t effective_stack;
  /*
   0 = hero to act, 1 = villain to act.
   */
  uint8_t to_act;
  /*
   Bet-tree version (0 = v0.1 defaults).
   */
  uint8_t bet_tree_version;
} HandState;

/*
 Output: strategy and derived quantities.
 */
typedef struct SolveResult {
  /*
   Solver version string ID (for consumer to verify compat).
   */
  uint32_t solver_version;
  /*
   Strategy: up to 8 actions, normalized to sum to 1.
   */
  uint8_t action_count;
  /*
   Per-action frequency.
   */
  float action_freq[8];
  /*
   Per-action expected value (in big blinds).
   */
  float action_ev[8];
  /*
   Hero's equity vs villain's range on this board.
   */
  float hero_equity;
  /*
   Exploitability at solve termination (lower = closer to Nash).
   */
  float exploitability;
  /*
   Iterations run.
   */
  uint32_t iterations;
  /*
   Wall-clock solve time, milliseconds.
   */
  uint32_t compute_ms;
} SolveResult;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Free a solver handle.

 Passing a null pointer is a no-op (matches standard C `free` semantics).
 */
void solver_free(struct SolverHandle *handle);

/*
 Look up a precomputed result from the cache.

 Returns `Ok` on hit, `CacheMiss` on miss (caller should call
 `solver_solve`), `InvalidInput` on malformed args.
 */
int32_t solver_lookup_cached(const struct HandState *_input, struct SolveResult *_output);

/*
 Create a new solver handle. Returns null on allocation failure.
 */
struct SolverHandle *solver_new(void);

/*
 Solve a spot live.

 Returns `SolverStatus::Ok` on success, `InvalidInput` on malformed
 arguments, `InternalError` if we caught a panic.

 # v0.1 caveats

 - River-only: `HandState.board_len` must be 5. Turn/flop subgames
   come with the cache (v0.2) and the turn subgame (v0.3).
 - `bet_tree_version` must be 0 (the default v0.1 tree). Other values
   are reserved for future tree profiles.
 - Iteration count is hardcoded to `DEFAULT_ITERATIONS` (100). See the
   constant's doc-comment for the ABI-stability rationale.
 - Any stack size is OK. A58's AllIn-terminal fix (commit `5629935`)
   bounds the river tree under arbitrary stack depths; the previous
   "stack=0 or small values" caveat is no longer accurate.

 # Safety

 `input` and `output` must either be null or point to a valid,
 correctly-aligned `HandState` / `SolveResult` respectively. The
 function null-checks them before dereferencing and returns
 `InvalidInput` on null — any other invalid pointer (dangling,
 misaligned, wrong size) is undefined behavior. This matches the C
 ABI contract the cbindgen-generated `solver.h` documents.
 */
int32_t solver_solve(struct SolverHandle *_handle,
                     const struct HandState *input,
                     struct SolveResult *output);

/*
 Version string. Null-terminated. Do not free.
 */
const char *solver_version(void);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* POKER_SOLVER_FFI_H */


