#!/usr/bin/env bash
#
# gh-release.sh — publish a GitHub Release for a version already built
# by scripts/build-release.sh.
#
# Usage:
#   scripts/gh-release.sh v0.1.0
#
# Preconditions:
#   - scripts/build-release.sh v0.1.0 has been run and the tarball +
#     sha256 sidecar exist under target/release-bundle/.
#   - `gh auth status` is authenticated against github.com with perms
#     to create releases on this repo.
#   - docs/RELEASE_NOTES_<VERSION>.md (preferred) or docs/RELEASE_NOTES.md
#     exists; otherwise a minimal auto-generated note is used.
#   - The git tag $VERSION already exists locally AND on origin. We do
#     not create the tag here — that's a human decision tied to
#     docs/RELEASE_PROCESS.md step order.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

if [[ $# -lt 1 || -z "${1:-}" ]]; then
    echo "usage: scripts/gh-release.sh <version>   e.g. v0.1.0" >&2
    exit 64
fi
VERSION="$1"

TARBALL="target/release-bundle/solver-$VERSION-macos-universal.tar.gz"
SHA_FILE="$TARBALL.sha256"
HEADER_SRC="crates/solver-ffi/include/solver.h"

# --- preflight ---------------------------------------------------------------
if ! command -v gh >/dev/null 2>&1; then
    echo "error: 'gh' (GitHub CLI) not installed" >&2
    echo "       install: brew install gh" >&2
    exit 2
fi

if ! gh auth status >/dev/null 2>&1; then
    echo "error: 'gh' is not authenticated. Run: gh auth login" >&2
    exit 2
fi

if [[ ! -f "$TARBALL" ]]; then
    echo "error: tarball not found: $TARBALL" >&2
    echo "       run: scripts/build-release.sh $VERSION" >&2
    exit 3
fi
if [[ ! -f "$SHA_FILE" ]]; then
    echo "error: sha sidecar not found: $SHA_FILE" >&2
    echo "       run: scripts/build-release.sh $VERSION" >&2
    exit 3
fi
if [[ ! -f "$HEADER_SRC" ]]; then
    echo "error: header missing at $HEADER_SRC (run build-release.sh first)" >&2
    exit 3
fi

# Refuse to publish if the tag doesn't exist — easy footgun to otherwise
# attach a tarball to a release pointing at a nonexistent ref.
if ! git rev-parse --verify --quiet "refs/tags/$VERSION" >/dev/null; then
    echo "error: git tag $VERSION does not exist locally" >&2
    echo "       create it: git tag -a $VERSION -m 'poker-solver $VERSION'" >&2
    echo "       push it:   git push origin $VERSION" >&2
    exit 4
fi

# Warn (but do not fail) if tag isn't pushed to origin yet — `gh release create`
# against an unpushed tag will fail anyway with a clearer error.
if ! git ls-remote --exit-code --tags origin "refs/tags/$VERSION" >/dev/null 2>&1; then
    echo "warning: tag $VERSION not found on origin — gh will likely fail." >&2
    echo "         consider: git push origin $VERSION" >&2
fi

# --- release notes -----------------------------------------------------------
# Prefer a version-specific file; fall back to a generic one; else synthesize.
NOTES_ARG=()
if [[ -f "docs/RELEASE_NOTES_$VERSION.md" ]]; then
    NOTES_ARG=(--notes-file "docs/RELEASE_NOTES_$VERSION.md")
elif [[ -f "docs/RELEASE_NOTES.md" ]]; then
    NOTES_ARG=(--notes-file "docs/RELEASE_NOTES.md")
else
    SHA_LINE="$(cat "$SHA_FILE")"
    NOTES_ARG=(--notes "poker-solver $VERSION

Universal macOS (arm64 + x86_64) release of solver-ffi for Poker Panel
integration. See docs/RELEASE_PROCESS.md for install instructions.

**tarball sha256:**
\`\`\`
$SHA_LINE
\`\`\`

Generated by scripts/gh-release.sh — no hand-authored release notes
were found under docs/RELEASE_NOTES_$VERSION.md or docs/RELEASE_NOTES.md.")
fi

echo "=== publishing GitHub Release $VERSION ==="
echo "tarball:  $TARBALL"
echo "sha:      $(cat "$SHA_FILE")"
echo "header:   $HEADER_SRC"
echo

gh release create "$VERSION" \
    --title "poker-solver $VERSION" \
    --verify-tag \
    "${NOTES_ARG[@]}" \
    "$TARBALL" \
    "$SHA_FILE" \
    "$HEADER_SRC"

echo
echo "=== release published ==="
echo "next: update crates/solver-ffi/Package.swift with the tarball sha256"
echo "      from $SHA_FILE, then commit + push."
